export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_CHANGED_SUCCESS = 'PASSWORD_CHANGED_SUCCESS';
//___________________________________________________

export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT_CATEGORIES_SUCCESS = 'FETCH_RESTAURANT_CATEGORIES_SUCCESS';
export const FETCH_RESTAURANT_BY_ID_INIT = 'FETCH_RESTAURANT_BY_ID_INIT';
export const GET_RESTAURANT_INFO_SUCCESS = 'GET_RESTAURANT_INFO_SUCCESS';
export const FETCH_RESTAURANT_PRODUCTS_SUCCESS = 'FETCH_RESTAURANT_PRODUCTS_SUCCESS';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
