/** *
		* AUTH
    */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const PASSWORD_CHANGED_SUCCESS = 'PASSWORD_CHANGED_SUCCESS';
export const PASSWORD_CHANGED_FAILURE = 'PASSWORD_CHANGED_FAILURE';
/** *
		* RESTAURANTS
    */

export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT_CATEGORIES_SUCCESS = 'FETCH_RESTAURANT_CATEGORIES_SUCCESS';
export const FETCH_RESTAURANT_BY_ID_INIT = 'FETCH_RESTAURANT_BY_ID_INIT';
export const GET_RESTAURANT_INFO_SUCCESS = 'GET_RESTAURANT_INFO_SUCCESS';
export const FETCH_RESTAURANT_PRODUCTS_SUCCESS = 'FETCH_RESTAURANT_PRODUCTS_SUCCESS';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const SYNC_QUANTITY = 'SYNC_QUANTITY';
export const HISTORY_ORDERS = 'HISTORY_ORDERS';
export const CHECKOUT_ORDER_SUCCESS = 'CHECKOUT_ORDER_SUCCESS';
